# Generated by Django 3.0.11 on 2021-08-07 21:40

import app.restaurants.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Table Number')),
                ('seats', models.IntegerField(validators=[app.restaurants.models.validate_seats_number], verbose_name='Seats Number')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(default=None, verbose_name='Reservation Start Time')),
                ('end', models.TimeField(default=None, verbose_name='Reservation End Time')),
                ('date', models.DateField(default=None, verbose_name='Reservation date')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table', to='restaurants.Table')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['start'],
            },
        ),
    ]
