# Generated by Django 3.0.11 on 2021-08-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210806_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rool',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee')], default='Admin', max_length=10, verbose_name='Role'),
            preserve_default=False,
        ),
    ]
